// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB11pipHQpR1ndV2Uai-yQ2mASvFNBkeGg',
    appId: '1:144171204328:web:2c0a4088029f320aae935d',
    messagingSenderId: '144171204328',
    projectId: 'signbuddy-7bced',
    authDomain: 'signbuddy-7bced.firebaseapp.com',
    storageBucket: 'signbuddy-7bced.appspot.com',
    measurementId: 'G-2L21QHZSWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCccm_FhvZNaB4OIw8a4u922KJAequm9js',
    appId: '1:144171204328:android:814b2126ed0149f5ae935d',
    messagingSenderId: '144171204328',
    projectId: 'signbuddy-7bced',
    storageBucket: 'signbuddy-7bced.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgBJV68pL9OG4Xud3T4K6KgJbGQFJfFXU',
    appId: '1:144171204328:ios:1175ce4d54521084ae935d',
    messagingSenderId: '144171204328',
    projectId: 'signbuddy-7bced',
    storageBucket: 'signbuddy-7bced.appspot.com',
    iosClientId: '144171204328-ooqa7em4m7q2o8i4f4m78ks1pk6bhttc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgBJV68pL9OG4Xud3T4K6KgJbGQFJfFXU',
    appId: '1:144171204328:ios:1175ce4d54521084ae935d',
    messagingSenderId: '144171204328',
    projectId: 'signbuddy-7bced',
    storageBucket: 'signbuddy-7bced.appspot.com',
    iosClientId: '144171204328-ooqa7em4m7q2o8i4f4m78ks1pk6bhttc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
